# Generated by Django 3.2.8 on 2021-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('application_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentToActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('user_status', models.CharField(default='普通用户', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('to_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField()),
            ],
        ),
    ]
