# Generated by Django 3.2.8 on 2021-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_application_commenttoactivity_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('banned_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('org_admin_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('comment_time', models.DateTimeField()),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('problem_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('parti_time', models.DateTimeField()),
            ],
        ),
    ]
