# Generated by Django 3.2.8 on 2021-11-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_banuser_feedback_participate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='organization_id',
            new_name='organization_name',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
