# Generated by Django 3.2.8 on 2021-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0006_auto_20211122_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_post',
            field=models.CharField(default=23, max_length=70),
            preserve_default=False,
        ),
    ]
