# Generated by Django 3.2.8 on 2021-11-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0007_activity_activity_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='parti_id',
            field=models.CharField(default=12, max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participate',
            name='activity_id',
            field=models.CharField(max_length=40),
        ),
    ]
