# Generated by Django 3.2.8 on 2021-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0010_auto_20211123_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participate',
            old_name='parti_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=20),
        ),
    ]
