# Generated by Django 3.2.8 on 2021-11-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0012_auto_20211124_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='father_comment_id',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.CharField(default='1', max_length=140),
        ),
        migrations.AlterField(
            model_name='reply',
            name='from_comment_id',
            field=models.CharField(default='1', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='to_comment_id',
            field=models.CharField(max_length=40),
        ),
    ]
