# Generated by Django 3.2.3 on 2021-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0013_auto_20211124_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentToActivity',
        ),
    ]
