# Generated by Django 3.2.3 on 2021-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0014_delete_commenttoactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
