# Generated by Django 3.2.3 on 2021-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0016_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_post',
            field=models.CharField(default='https://img1.baidu.com/it/u=2065540330,1405717749&fm=26&fmt=auto', max_length=70),
        ),
    ]
