# Generated by Django 3.2.3 on 2021-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0018_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_post',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
